# Generated by Django 4.2.5 on 2023-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(default='', max_length=14),
        ),
    ]
